server:
  port: 8085
  servlet:
    context-path: /starter
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  server:
    port: 9085
    base-path: /
app:
  version: @version@
spring:
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_absent
  application:
    name: Portal Starter
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  session:
    store-type: none
  aop:
    proxy-target-class: false
pru:
  servlet:
    pub-api-path: /api
    prv-api-path: /
  ap:
    rest:
      basePath: ${pru.servlet.pub-api-path}
elastic:
  apm:
    config:
      enabled: ${APM_ENABLED:true}
      server_url: ${APM_SERVER_URL}
      service_name: ${APP_NAME}
      service_version: ${app.version}
      secret_token: ${APM_SECRET_TOKEN}
      environment: ${APM_ENVIRONMENT}
      application_packages: pl.aswit.starter
      log_level: ${APM_LOG_LEVEL}
      enable_log_correlation: true
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:false}
logging:
  pattern:
    level: "[%X{transaction.id} %X{trace.id}] %5p"
#  level: # TODO PLACE FEIGN CLIENTS HERE
#    com:
#      pru:
#        cas:
#          sso:
#            provider:
#              pruuser:
#                PruUserClient: DEBUG
